export const SET_MOVIES = 'SET_MOVIES';
export const SET_MOVIE_DETAIL = 'SET_MOVIE_DETAIL';
export const REMOVE_MOVIE_DETAIL = 'REMOVE_MOVIE_DETAIL';

export const SET_QUERY_SEARCH = 'SET_QUERY_SEARCH';

export const INCREMENT_LOADING = 'INCREMENT_LOADING';
export const DECREMENT_LOADING = 'DECREMENT_LOADING';